### ISSUE TITLE
website not functioning

### ISSUE THREAD

**Issue by guer0125** [guer0125/kraken-good-accessibility#1]
I'm getting an error from markbot saying the website is not functioning as expected. the element, header nav:last-of-type a:not (.current) doesn't exist on this page.

not sure what it's referring to?

@HannahDelaney

**Comment by guer0125** [comment]
so that worked well, but not im getting that main must not appear as a descendant  of article

article
  main

  main
article

is the way i have it, because i noticed that in order for other css to work the article had to be all around the Ps which makes sense.

**Comment by guer0125** [comment]
also, chapter is not changing colour even though the target is now correct. and everything else does change to white

**Comment by HannahDelaney** [comment]
So the main tag is actually not necessary semantically for an article like this, and isn't in this assignment. If you were publishing an online article or in a magazine, it wouldn't necessarily be the main content, it would be an article of many...I believe that is part of the logic on that one. Definitely not immediately obvious though.

Change your `<main role="main">` to be `<div role="main">` to solve that problem.

As for the Chapter colour, there is a piece in the html that will fix that. If you change the `<div>` around your `<h1>` and `<h2>` to be something called `<hgroup>`, it should fix the problem. It's just a way to collect your headings together, explained a bit more here: https://www.w3docs.com/learn-html/html-hgroup-tag.html

Also, little hint (since I predict this will come up next): This assignment has two footers. One is inside the article, and one is outside of it, with just the `<small>` copy in it...

**Comment by guer0125** [comment]
thanks a ton.

so now its saying the contrast of the header background colour is not enough for the text. i changed it to   background-color: #259f95; which is the one used for the nav. and even-though it changes when i inspect it. markbot doesn't think it's enough contrast. i changed it to black and it's giving me the same error.

**Comment by HannahDelaney** [comment]
I was curious why this was happening because it should be happy (it just wants a `background-color` in case the image can't display) so I tested it in Markbot. If you look closely, I think you'll find that the error isn't for the header when you make the `background-color: #1e7c74;`, it actually says this issue is now being applied to the _footer_.

Keep the actual colour (ie not black) on your header, and then add a `background-color` to your footer as well. It uses a `background-image` too, so should have a backup colour so the text is visible either way. You may notice your screenshot is actually closer to the sample now as well.
